import streamlit as st
import json
from pathlib import Path
from datetime import datetime
import uuid
import time

st.set_page_config("Order Application",layout="wide",initial_sidebar_state="expanded")

inventory = [
    {"item_id": 1, "name": "Espresso", "unit_price": 2.50, "stock": 40},
    {"item_id": 2, "name": "Latte", "unit_price": 4.25, "stock": 25},
    {"item_id": 3, "name": "Cold Brew", "unit_price": 3.75, "stock": 30},
    {"item_id": 4, "name": "Mocha", "unit_price": 4.50, "stock": 20},
    {"item_id": 5, "name": "Blueberry Muffin", "unit_price": 2.95, "stock": 18},
]

if "page" not in st.session_state:
    st.session_state["page"] = "home"

if "messages" not in st.session_state:
    st.session_state["messages"] = ({

        "role": "assistant",
        "content": "Hi! How can I help you?"
    })


with st.sidebar:
    if st.button("Home", key="home_btn",type="primary",use_container_width=True):
        st.session_state["page"] = "home"
        st.rerun()

    if st.button("Orders", key="order_btn",type="primary",use_container_width=True):
        st.session_state["page"] = "orders"
        st.rerun()

json_path_inventory = Path("inventory.json")
if json_path_inventory.exists():
    with open(json_path_inventory, "r") as f:
        inventory = json.load(f)

json_path_orders = Path("orders.json")
if json_path_orders.exists():
    with open(json_path_orders,"r") as f:
        orders = json.load(f)
else:
    orders = []    

if st.session_state["page"] == "home":
    col1 , col2 = st.columns([4,2])
    with col1:
        selected_category = st.radio("Select a Category",["Orders","Inventory"],horizontal=True)

        if selected_category == "Inventory":
            st.markdown("## Inventory")
            if len(inventory) > 0:
                st.dataframe(inventory)
            else:
                st.warning("No item is found")
        else:
            st.markdown("## Orders")
            if len(orders) > 0:
                st.dataframe(orders)
            else:
                st.warning("No Orders are recorded yet")
    with col2:
        if selected_category == "Inventory":
            st.metric("Total Inventory", f"{len(inventory)}")
        else:
            st.metric("Total Orders", f"{len(orders)}")
        

elif st.session_state["page"] == "orders":
    st.markdown("Under Construction...")

    tab1, tab2 = st.tabs(["Add New Order", "Cancel an Order"])

    with tab1:
        col1, col2 = st.columns([3,3])
        with col1:

            selected_item = st.selectbox("Items", options=inventory,key="Inventory_selector",format_func=lambda x: f"{x['name']}")
            quantity = st.number_input("Enter the Quantity", min_value=1, step=1)
            if st.button("Create new order", key="create_order_btn", type="primary", use_container_width=True):
                with st.spinner("recording the new order.."):
                    total = quantity * selected_item["unit_price"]

                    for item in inventory: 
                        if item["item_id"] == selected_item["item_id"]:
                            item["stock"] = item["stock"] - quantity
                            break
                    orders.append({
                        "id": str(uuid.uuid4()),
                        "item_id" : selected_item["item_id"],
                        "quantity": quantity,
                        "status": "placed",
                        "total" : total

                    })
        with col2:
            st.subheader("AI Assistant")
            col11, col22 = st.columns([3,1])
            with col11:
                st.caption("Try asking: How do I place an order?")
            with col22:
                if st.button("Clear Messages"):
                    pass
            with st.container(border=True, height = 250):
                for message in st.session_state["messages"]:
                    with st.chat_message(message["role"]):
                        st.write(message["content"])

            user_input = st.chat_input("Ask a question...")
            if user_input:
                with st.spinner("thinking..."):
                    st.session_state["messages"].append(
                        {
                            "role": "user", 
                            "content": user_input
                        }
                    )
                    ai_response = "I am working on it"
                    ##response is generated by ai
                    st.session_state["messages"].append(
                        {
                            "role": "assistant", 
                            "content": ai_response
                        }
                    )
                    time.sleep(2)
                    st.rerun()



    with tab2:
        pass